### ISSUE TITLE
Support for Crystal 1.0.0

### ISSUE THREAD

**Issue by plambert** [spider-gazelle/crystal-ldap#5]
What needs to be done to be able to use this shard with Crystal 1.0.0 without the `--ignore-crystal-version` flag?

Does it require testing?  Or just a metadata update?

**Comment by stakach** [comment]
should already work with crystal 1.0.0 without needing `--ignore-crystal-version`

**Comment by plambert** [comment]
Then why was https://github.com/spider-gazelle/crystal-ldap/commit/e46686aaced1398dfd85509a19f96ce920bff288 added?

On my system `shards update` gives me:

```
- `crystal (>= 0.36.1)` required by `ldap 0.9.1`
```

My understanding is that `>=0.36.1` doesn't mean "all future versions for eternity" but "all minor and patch versions above this one."  `1.0.0` does not satisfy `>=0.36.1`.  Am I wrong?

**Comment by plambert** [comment]
No... you're right, ignore me.  Removing all my other dependencies, it installs fine, so the problem has to be somewhere else.  I'll track it down.

**Comment by stakach** [comment]
The trick is to run `shards update --ignore-crystal-version` and then it should give you a list of the possibly incompatible shards at the end of the update

i.e. `Shard "CrystalEmail" may be incompatible with Crystal 1.0.0`
